#!/usr/bin/env python3
"""Convert notes/spine/*.md to article LaTeX (not the book chapter map).

Book ``md_to_latex.py`` maps ``#`` → ``\\chapter``. Under ``article`` that
counter stays 0, so body became 0.1–0.6 and the appendix title vanished.

Spine map:

- drop the markdown ``#`` title (titlepage is in ``main.tex``)
- body ``##`` → ``\\section`` (1–5); ``###`` → ``\\subsection``
- ``## References`` → ``\\section*``
- appendix: ``\\section*{Appendix --- Models and hypotheses}`` then
  ``\\renewcommand{\\thesection}{A.\\arabic{section}}`` and ``##`` → A.1–A.5

Usage (from repo root):
  python3 scripts/spine_md_to_latex.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from md_to_latex import convert_file  # noqa: E402

SPINE = ROOT / "notes" / "spine"
OUT = SPINE / "latex"

_CHAPTER_TITLE = re.compile(
    r"\\chapter\*?\{[^}]*\}\s*\\label\{[^}]*\}\s*",
    re.MULTILINE,
)


def _blockquotes_to_quote_env(md: str) -> str:
    """Turn Markdown ``> `` lines into a quote env convert_file will pass through."""
    out: list[str] = []
    buf: list[str] = []

    def flush() -> None:
        if not buf:
            return
        out.append(r"\begin{quote}")
        out.extend(buf)
        out.append(r"\end{quote}")
        buf.clear()

    for line in md.splitlines():
        if line.startswith("> "):
            buf.append(line[2:])
        elif line.strip() == ">":
            buf.append("")
        else:
            flush()
            out.append(line)
    flush()
    return "\n".join(out) + "\n"


def _drop_title_chapter(tex: str, md_name: str) -> str:
    tex, n = _CHAPTER_TITLE.subn("", tex, count=1)
    if n != 1:
        raise SystemExit(f"{md_name}: expected one \\chapter title to drop, got {n}")
    return tex


def _unnumbered_references(tex: str) -> str:
    return re.sub(
        r"\\section\{References[^}]*\}",
        lambda m: m.group(0).replace(r"\section{", r"\section*{", 1),
        tex,
        count=1,
    )


def _soften_code_breaks(tex: str) -> str:
    """Do not split ``HATCHER_MAP.md``, pins, or version dots mid-token.

    Book ``latex_code_span`` inserts ``\\allowbreak`` after ``.`` and ``\\_``.
    Keep breaks after ``/`` and ``:`` so long paths can still wrap.
    """
    tex = tex.replace(r".\allowbreak{}", ".")
    tex = tex.replace(r"\_\allowbreak{}", r"\_")
    return tex


def _mbox_git_pins(tex: str) -> str:
    tex = tex.replace(r"qga\_engine@7e7866b", r"\mbox{qga\_engine@7e7866b}")
    tex = tex.replace(r"qga\_gpu@b9c9994", r"\mbox{qga\_gpu@b9c9994}")
    return tex


_HATCHER_TN_URL = "https://pi.math.cornell.edu/~hatcher/TN/TNbook.pdf"
_HATCHER_TN_HREF = (
    r"\href{https://pi.math.cornell.edu/~hatcher/TN/TNbook.pdf}"
    r"{\texttt{https://pi.math.cornell.edu/\allowbreak"
    r"\textasciitilde{}hatcher/\mbox{TN/TNbook.pdf}}}"
)


def _hatcher_url_break(tex: str) -> str:
    """Keep ``TN/TNbook.pdf`` as one token; wrap after ``~hatcher/``."""
    tex = tex.replace(r"\url{" + _HATCHER_TN_URL + "}", _HATCHER_TN_HREF)
    tex = tex.replace(
        r"\url{https://pi.math.cornell.edu/\~hatcher/TN/TNbook.pdf}",
        _HATCHER_TN_HREF,
    )
    return tex


def _clearpage_before_first_section(tex: str) -> str:
    """Appendix title page must not share a running head with A.1."""
    return tex.replace(r"\section{", r"\clearpage" + "\n" + r"\section{", 1)


def convert_spine(md_name: str, label: str) -> str:
    md_path = SPINE / md_name
    raw = _blockquotes_to_quote_env(md_path.read_text(encoding="utf-8"))
    tmp = OUT / f".{md_name}.tmp"
    tmp.write_text(raw, encoding="utf-8")
    try:
        tex = convert_file(tmp, kind="chapter", label_base=label)
    finally:
        tmp.unlink(missing_ok=True)
    tex = tex.replace(
        f"% Auto-generated from book/.{md_name}.tmp",
        f"% Auto-generated from notes/spine/{md_name}",
    )
    tex = tex.replace(
        "% Regenerated by scripts/md_to_latex.py",
        "% Regenerated by scripts/spine_md_to_latex.py — article heading map, not book chapters",
    )
    tex = _drop_title_chapter(tex, md_name)
    tex = _unnumbered_references(tex)
    tex = _soften_code_breaks(tex)
    tex = _mbox_git_pins(tex)
    tex = _hatcher_url_break(tex)
    if md_name == "appendix_models.md":
        tex = _clearpage_before_first_section(tex)
    return tex


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    body = convert_spine("spine.md", "ch:spine")
    (OUT / "body.tex").write_text(body, encoding="utf-8")
    print(f"wrote notes/spine/latex/body.tex ({len(body.splitlines())} lines)")

    app = convert_spine("appendix_models.md", "ch:appendix")
    (OUT / "appendix.tex").write_text(app, encoding="utf-8")
    print(f"wrote notes/spine/latex/appendix.tex ({len(app.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
